import type { Metadata } from "next"
import Link from "next/link"

export const metadata: Metadata = {
  title: "Terms of Service - YouTube Summaries",
  description: "Terms of Service for YouTube Summaries - Please read our terms and conditions carefully.",
}

export default function TermsOfService() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="mb-8">
        <Link href="/" className="text-primary hover:underline">
          ← Back to Home
        </Link>
      </div>

      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>

      <div className="prose prose-slate dark:prose-invert max-w-none">
        <p className="text-sm text-muted-foreground mb-6">
          Last updated: {new Date().toLocaleDateString()}
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using YouTube Summaries (&quot;the Service&quot;), you accept and agree to be bound by the terms
          and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          YouTube Summaries is a web application that extracts transcripts and generates AI-powered summaries from
          YouTube videos. The service is provided &quot;as is&quot; and is intended for personal, educational, and research use.
        </p>

        <h2>3. User Responsibilities</h2>
        <p>You agree to:</p>
        <ul>
          <li>Use the service only for lawful purposes</li>
          <li>Not attempt to reverse engineer, decompile, or disassemble the service</li>
          <li>Not use the service to infringe on the rights of others</li>
          <li>Not upload or share content that violates YouTube&apos;s terms of service</li>
          <li>Respect the intellectual property rights of content creators</li>
        </ul>

        <h2>4. Content and Copyright</h2>
        <p>
          The transcripts and summaries generated by our service are derived from YouTube video content. We do not
          claim ownership of the original content. Users are responsible for ensuring their use of generated content
          complies with applicable copyright laws and YouTube&apos;s terms of service.
        </p>

        <h2>5. AI-Generated Content Disclaimer</h2>
        <p>
          AI-generated summaries are provided for informational purposes only. While we strive for accuracy, AI
          summaries may contain errors or inaccuracies. Users should verify important information through the original
          video content and should not rely solely on AI summaries for critical decisions.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          YouTube Summaries shall not be liable for any direct, indirect, incidental, special, consequential, or
          exemplary damages resulting from your use of the service. This includes but is not limited to damages for
          loss of profits, goodwill, use, data, or other intangible losses.
        </p>

        <h2>7. Service Availability</h2>
        <p>
          We strive to maintain high availability of our service, but we do not guarantee uninterrupted or error-free
          operation. The service may be temporarily unavailable due to maintenance, technical issues, or factors
          beyond our control.
        </p>

        <h2>8. Privacy</h2>
        <p>
          Your privacy is important to us. Please review our
          <Link href="/privacy-policy" className="text-primary hover:underline"> Privacy Policy</Link>,
          which also governs your use of the service, to understand our practices.
        </p>

        <h2>9. Modifications to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. Changes will be effective immediately upon posting
          on this page. Your continued use of the service after changes constitutes acceptance of the new terms.
        </p>

        <h2>10. Termination</h2>
        <p>
          We may terminate or suspend your access to the service immediately, without prior notice or liability,
          for any reason whatsoever, including without limitation if you breach the terms.
        </p>

        <h2>11. Governing Law</h2>
        <p>
          These terms shall be interpreted and governed by the laws of the jurisdiction in which YouTube Summaries
          operates, without regard to conflict of law provisions.
        </p>

        <h2>12. Contact Information</h2>
        <p>
          If you have any questions about these Terms of Service, please contact us through our
          <Link href="/contact" className="text-primary hover:underline"> contact page</Link>.
        </p>
      </div>
    </div>
  )
}